# Based on the appveyor.yml example at
# https://www.appveyor.com/docs/lang/nodejs-iojs/

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

# Install scripts. These runs after repo cloning.
install:
  # Install Chrome for testing purposes.
  # Firefox should already be installed.
  - choco install --ignore-checksum googlechrome
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  - node --version
  - npm --version
  # Install modules.
  - npm install
  # Install gulp.
  - npm install -g gulp
  # Install serve for running the Selenium tests.
  - npm install -g serve@6.5.3

# Build scripts. These run after installation.
build_script:
  # Compile sources.
  - gulp lint build build-test

# Post-install test scripts.
test_script:
  # Run tests.
  - gulp test
  # Run the Selenium tests.
  - start /b serve -s build -p 8080 &&
    pushd selenium && run-ci.bat https://localhost:8080/index.html && popd &&
    taskkill /F /IM serve /T
